name: Tests

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  # schedule:
  #   - cron: '0 6 * * 0'

jobs:
  build:
    name: Run build
    uses: ./.github/workflows/build.yml

  test:
    name: Execute tests
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: pnpm run test
